/*******************************************************************************
 * Copyright (c) 2006, 2024 ETH Zurich and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     ETH Zurich - initial API and implementation
 *******************************************************************************/
package org.eventb.internal.ui.prooftreeui;

import static java.util.stream.Collectors.joining;

import java.util.Set;

import org.eclipse.jface.viewers.Viewer;
import org.eclipse.jface.viewers.ViewerFilter;
import org.eventb.core.seqprover.IProofRule;
import org.eventb.core.seqprover.IProofTreeNode;

public class RuleFilter extends ViewerFilter {

	protected final String reasonerName;

	protected final Set<String> reasonerIDs;

	public RuleFilter(String reasonerName, Set<String> reasonerIDs) {
		this.reasonerName = reasonerName;
		this.reasonerIDs = reasonerIDs;
	}

	@Override
	public boolean select(Viewer viewer, Object parentElement, Object element) {
		if (ProofTreeUIUtils.DEBUG)
			ProofTreeUIUtils.debug("Filtered reasoner IDs: " + reasonerIDs.stream().collect(joining(", ")));
		if (element instanceof IProofTreeNode) {
			IProofTreeNode node = (IProofTreeNode) element;
			if (node.isOpen()) {
				return true; // Do not filter open node
			}
			IProofRule rule = node.getRule();
			if (ProofTreeUIUtils.DEBUG) {
				ProofTreeUIUtils.debug("Rule display" + node.getRule().getDisplayName());
				ProofTreeUIUtils.debug("Generated by reasoner: " + rule.generatedBy().getReasonerID());
			}
			return !reasonerIDs.contains(rule.generatedBy().getReasonerID());
		}
		return true;
	}

	@Override
	public String toString() {
		return reasonerName;
	}

}
