<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="api"
    nsURI="http://emf.core.rodinp.org/models/lightcore/api" nsPrefix="org.rodinp.core.emf.lightcore.api">
  <eClassifiers xsi:type="ecore:EClass" name="ILElement" abstract="true" interface="true">
    <eOperations name="getChildren">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getEChildren();"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments>
          <eUpperBound eClassifier="#//ILElement"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="getAttributes">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final EMap&lt;String, Attribute> attributes = getEAttributes();&#xA;final List&lt;IAttributeValue> values = new ArrayList&lt;IAttributeValue>(&#xA;&#x9;&#x9;attributes.size());&#xA;for (Attribute att : attributes.values()) {&#xA;&#x9;final IAttributeValue value = valueOf(att);&#xA;&#x9;values.add(value);&#xA;}&#xA;return values;"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//IAttributeValue"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getAttribute" eType="#//IAttributeValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return valueOf(attribute);"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType"/>
    </eOperations>
    <eOperations name="getAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return (Boolean) attribute.getValue();"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType_Boolean"/>
    </eOperations>
    <eOperations name="getAttribute" eType="#//IRodinElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return (IRodinElement) attribute.getValue();"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType_Handle"/>
    </eOperations>
    <eOperations name="getAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return (Integer) attribute.getValue();"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType_Integer"/>
    </eOperations>
    <eOperations name="getAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return (Long) attribute.getValue();"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType_Long"/>
    </eOperations>
    <eOperations name="getAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final Attribute attribute = getEAttributes().get(type.getId());&#xA;if (attribute == null)&#xA;&#x9;return null;&#xA;return (String) attribute.getValue();"/>
      </eAnnotations>
      <eParameters name="type" eType="#//IAttributeType_String"/>
    </eOperations>
    <eOperations name="setAttribute">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final IAttributeType type = value.getType();&#xA;Attribute attribute = getEAttributes().get(type.getId());&#xA;final Object new_value = value.getValue();&#xA;final Object old_value = (attribute != null) ? attribute.getValue()&#xA;&#x9;: null;&#xA;if (new_value == null || new_value.equals(old_value)) {&#xA;&#x9;return;&#xA;}&#xA;if (attribute == null) {&#xA;&#x9;attribute = LightcoreFactory.eINSTANCE.createAttribute();&#xA;&#x9;attribute.setOwner(this);&#xA;&#x9;attribute.setType(type);&#xA;}&#xA;attribute.setValue(value.getValue());&#xA;getEAttributes().put(type.getId(), attribute);"/>
      </eAnnotations>
      <eParameters name="value" eType="#//IAttributeValue"/>
    </eOperations>
    <eOperations name="getElement" eType="#//IInternalElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (IInternalElement) getERodinElement();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="delete">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EcoreUtil.delete(this, true);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="moveChild">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final EList&lt;LightElement> children = getEChildren();&#xA;children.move(newPos, oldPos);"/>
      </eAnnotations>
      <eParameters name="newPos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="oldPos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isImplicit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getChildrenOfType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final List&lt;ILElement> list = new &lt;%java.util.ArrayList%>&lt;ILElement>();&#xA;for (ILElement child : getChildren()) {&#xA;&#x9;if (child.getElement().getElementType() == type) {&#xA;&#x9;&#x9;list.add(child);&#xA;&#x9;}&#xA;}&#xA;return list;"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//ILElement"/>
      </eGenericType>
      <eParameters name="type">
        <eGenericType eClassifier="#//IInternalElementType">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getElement().getElementType();"/>
      </eAnnotations>
      <eGenericType eClassifier="#//IInternalElementType">
        <eTypeArguments>
          <eUpperBound eClassifier="#//IInternalElement"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="createChild" lowerBound="1" eType="#//ILElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final IInternalElement internalNextSibling = (nextSibling == null) ? null&#xA;&#x9;&#x9;: nextSibling.getElement();&#xA;try {&#xA;&#x9;final IInternalElement child = getElement().createChild(type,&#xA;&#x9;&#x9;&#x9;internalNextSibling, null);&#xA;&#x9;final InternalElement loaded = SynchroManager&#xA;&#x9;&#x9;&#x9;.loadInternalElementFor(child, eRoot);&#xA;&#x9;this.addElement(loaded, nextSibling);&#xA;&#x9;return loaded;&#xA;} catch (RodinDBException e) {&#xA;&#x9;e.printStackTrace();&#xA;}&#xA;return null;"/>
      </eAnnotations>
      <eParameters name="type" lowerBound="1">
        <eGenericType eClassifier="#//IInternalElementType">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="nextSibling" eType="#//ILElement"/>
    </eOperations>
    <eOperations name="getParent" eType="#//ILElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getEParent();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType" instanceClassName="org.rodinp.core.IAttributeType"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeValue" instanceClassName="org.rodinp.core.IAttributeValue"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IInternalElement" instanceClassName="org.rodinp.core.IInternalElement"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IInternalElementType" instanceClassName="org.rodinp.core.IInternalElementType"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType_Boolean" instanceClassName="org.rodinp.core.IAttributeType.Boolean"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType_Handle" instanceClassName="org.rodinp.core.IAttributeType.Handle"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType_Integer" instanceClassName="org.rodinp.core.IAttributeType.Integer"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType_Long" instanceClassName="org.rodinp.core.IAttributeType.Long"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType_String" instanceClassName="org.rodinp.core.IAttributeType.String"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IRodinElement" instanceClassName="org.rodinp.core.IRodinElement"
      serializable="false"/>
</ecore:EPackage>
