<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="api"
    nsURI="http://emf.core.rodinp.org/models/lightcore/api" nsPrefix="org.rodinp.core.emf.lightcore.api">
  <eClassifiers xsi:type="ecore:EClass" name="ILElement" abstract="true" interface="true">
    <eOperations name="getChildren">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getEChildren();"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments>
          <eUpperBound eClassifier="#//ILElement"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="getAttributes">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final EMap&lt;String, Attribute> attributes = getEAttributes();&#xA;final List&lt;IAttributeValue> values = new &lt;%java.util.ArrayList%>&lt;IAttributeValue>(&#xA;&#x9;&#x9;attributes.size());&#xA;for (Attribute att : attributes.values()) {&#xA;&#x9;values.add((IAttributeValue) att.getValue());&#xA;}&#xA;return values;"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//IAttributeValue"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getAttribute" eType="#//IAttributeValue">
      <eParameters name="type" eType="#//IAttributeType"/>
    </eOperations>
    <eOperations name="setAttribute">
      <eParameters name="value" eType="#//IAttributeValue"/>
    </eOperations>
    <eOperations name="getElement" eType="#//IInternalElement"/>
    <eOperations name="delete">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="int i = 2;&#xA;i++;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="moveChild">
      <eParameters name="newPos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="oldPos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isImplicit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeType" instanceClassName="org.rodinp.core.IAttributeType"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IAttributeValue" instanceClassName="org.rodinp.core.IAttributeValue"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IInternalElement" instanceClassName="org.rodinp.core.IInternalElement"
      serializable="false"/>
</ecore:EPackage>
