#!/usr/bin/perl -W
#
#  Generates test cases for the visitor.
#

use integer;
use strict;

sub gen_test($$);

my %params;
my %count;

open F, "constr.txt" or die "Can't open constr.txt: $!";
while (<F>) {
    chomp;
    next if m/^\s*$/;
    my ($class, $params, $count) = split("\t");
    $params{$class} = $params;
    $count{$class} = $count;
}
close F;

while (<>) {
    next if m/^\s*$/;
    my ($nat, $class, $tag, $name) = split;
    gen_test($class, $tag);
}


sub gen_test($$) {
    my ($class, $tag) = @_;
    my $param;
    if ($params{$class} eq '') {
	$param = "null";
    } else {
	$param = "$params{$class}, null";
    }
    print <<EOT;
	new TestItem(
		ff.make$class(Formula.$tag, $param),
		$count{$class}
	),
EOT
}
