/*******************************************************************************
 * Copyright (c) 2006, 2014 ETH Zurich and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     ETH Zurich - initial API and implementation
 *******************************************************************************/
package org.eventb.internal.core.seqprover.eventbExtensions;

import java.util.Arrays;

import org.eventb.core.ast.Predicate;
import org.eventb.core.seqprover.IHypAction;
import org.eventb.core.seqprover.IProverSequent;
import org.eventb.core.seqprover.ProverFactory;
import org.eventb.core.seqprover.ProverRule;
import org.eventb.core.seqprover.SequentProver;
import org.eventb.core.seqprover.IProofRule.IAntecedent;
import org.eventb.core.seqprover.eventbExtensions.Lib;
import org.eventb.core.seqprover.reasonerInputs.HypothesisReasoner;


/**
 * Generates a proof rule to eliminate a given disjunctive hypothesis by performing a case distinction
 * on its disjuncts.
 * 
 * <p>
 * Proof rules generated by this reasoner are not goal dependent.
 * </p>
 * 
 * @author Farhad Mehta
 *
 */
public class DisjE extends HypothesisReasoner {
	
	public static final String REASONER_ID = SequentProver.PLUGIN_ID + ".disjE";
	
	@Override
	public String getReasonerID() {
		return REASONER_ID;
	}
	
	@ProverRule("CASE")
	@Override
	protected IAntecedent[] getAntecedents(IProverSequent sequent,
			Predicate pred) throws IllegalArgumentException {

		if (pred == null) {
			throw new IllegalArgumentException("Null hypothesis");
		}
		if (!Lib.isDisj(pred)) {
			throw new IllegalArgumentException(
					"Hypothesis is not a disjunction: " + pred);
		}

		final Predicate[] disjuncts = Lib.disjuncts(pred);

		final int length = disjuncts.length;
		final IAntecedent[] antecedents = new IAntecedent[length];
		final IHypAction action = ProverFactory.makeDeselectHypAction(Arrays.asList(pred));
		for (int i = 0; i < length; i++) {
			antecedents[i] = ProverFactory.makeAntecedent(null, Lib
					.breakPossibleConjunct(disjuncts[i]), action);
		}
		return antecedents;
	}

	@Override
	protected String getDisplay(Predicate pred) {
		return "∨ hyp (" + pred + ")";
	}
	
	@Override
	protected boolean isGoalDependent(IProverSequent sequent, Predicate pred) {
		return false;
	}

}
