/*******************************************************************************
 * Copyright (c) 2005, 2009 ETH Zurich and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     ETH Zurich - initial API and implementation
 *     Systerel - corrected: hid original hyp, added impLeft hyp (ver 0)
 *     Systerel - visibility: deselected impLeft hyp (ver 1)
 *******************************************************************************/
package org.eventb.internal.core.seqprover.eventbExtensions;

import static java.util.Arrays.asList;
import static java.util.Collections.singleton;
import static org.eventb.core.seqprover.ProverFactory.makeDeselectHypAction;
import static org.eventb.core.seqprover.ProverFactory.makeHideHypAction;

import java.util.LinkedHashSet;
import java.util.Set;

import org.eventb.core.ast.Predicate;
import org.eventb.core.seqprover.IHypAction;
import org.eventb.core.seqprover.IProverSequent;
import org.eventb.core.seqprover.IVersionedReasoner;
import org.eventb.core.seqprover.ProverFactory;
import org.eventb.core.seqprover.ProverRule;
import org.eventb.core.seqprover.SequentProver;
import org.eventb.core.seqprover.IProofRule.IAntecedent;
import org.eventb.core.seqprover.eventbExtensions.Lib;
import org.eventb.core.seqprover.reasonerInputs.HypothesisReasoner;

/**
 * Generates a proof rule for modus ponens for a given implicative hypothesis.
 * 
 * <p>
 * Proof rules generated by this reasoner are not goal dependent.
 * </p>
 * 
 * @author Farhad Mehta
 *
 */
public class ImpE extends HypothesisReasoner implements IVersionedReasoner {
	
	public static String REASONER_ID = SequentProver.PLUGIN_ID + ".impE";
	private static final int VERSION = 1;
	
	public String getReasonerID() {
		return REASONER_ID;
	}

	@ProverRule("MH")
	@Override
	protected IAntecedent[] getAntecedents(IProverSequent sequent,
			Predicate pred) throws IllegalArgumentException {
		
		if (pred == null) {
			throw new IllegalArgumentException("Null hypothesis");
		}
		if (!Lib.isImp(pred)) {
			throw new IllegalArgumentException(
					"Hypothesis is not an implication: " + pred);
		}

		// Generate the antecedents
		final IAntecedent[] antecedents = new IAntecedent[2];
		
		final IHypAction hideHypAction = makeHideHypAction(singleton(pred));
		final Predicate impLeft = Lib.impLeft(pred);
		final Predicate impRight = Lib.impRight(pred);

		// impLeft goal
		antecedents[0] = ProverFactory.makeAntecedent(
				impLeft,
				null,
				hideHypAction);
		
		// continuation
		final Set<Predicate> impLeftPreds = Lib.breakPossibleConjunct(impLeft);
		final Set<Predicate> impRightPreds = Lib.breakPossibleConjunct(impRight);

		final Set<Predicate> addedHyps = new LinkedHashSet<Predicate>();
		addedHyps.addAll(impLeftPreds);
		addedHyps.addAll(impRightPreds);
		final IHypAction deselect = makeDeselectHypAction(impLeftPreds);
		
		antecedents[1] = ProverFactory.makeAntecedent(
				null,
				addedHyps,
				null,
				asList(hideHypAction, deselect));
		
		return antecedents;
	}

	@Override
	protected String getDisplay(Predicate pred) {
		return "⇒ hyp mp (" + pred + ")";
	}
	
	@Override
	protected boolean isGoalDependent(IProverSequent sequent, Predicate pred) {
		return false;
	}

	public int getVersion() {
		return VERSION;
	}

}
