/*******************************************************************************
 * Copyright (c) 2005, 2009 ETH Zurich and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     ETH Zurich - initial API and implementation
 *     Systerel - corrected: hid original hyp and added notImpRight hypothesis
 *******************************************************************************/
package org.eventb.internal.core.seqprover.eventbExtensions;

import static java.util.Collections.singleton;
import static org.eventb.core.seqprover.ProverFactory.makeHideHypAction;

import java.util.LinkedHashSet;
import java.util.Set;

import org.eventb.core.ast.Predicate;
import org.eventb.core.seqprover.IHypAction;
import org.eventb.core.seqprover.IProverSequent;
import org.eventb.core.seqprover.IVersionedReasoner;
import org.eventb.core.seqprover.ProverFactory;
import org.eventb.core.seqprover.ProverRule;
import org.eventb.core.seqprover.SequentProver;
import org.eventb.core.seqprover.IProofRule.IAntecedent;
import org.eventb.core.seqprover.eventbExtensions.Lib;
import org.eventb.core.seqprover.reasonerInputs.HypothesisReasoner;

/**
 * Generates a proof rule for modus tollens for a given implicative hypothesis.
 * 
 * <p>
 * Proof rules generated by this reasoner are not goal dependent.
 * </p>
 * 
 * <p>
 * Implementation is similar to the one in {@link ImpE}.
 * </p>
 * 
 * @author Farhad Mehta
 *
 */
// TODO : Rename to impEcontrapositive to be uniform with impE
public class ModusTollens extends HypothesisReasoner implements IVersionedReasoner {

	public static String REASONER_ID = SequentProver.PLUGIN_ID + ".mt";
	private static final int VERSION = 0;

	public String getReasonerID() {
		return REASONER_ID;
	}

	@ProverRule("HM")
	@Override
	protected IAntecedent[] getAntecedents(IProverSequent sequent,
			Predicate pred) throws IllegalArgumentException {

		if (pred == null) {
			throw new IllegalArgumentException("Null hypothesis");
		}
		if (!Lib.isImp(pred)) {
			throw new IllegalArgumentException(
					"Hypothesis is not an implication: " + pred);
		}

		final IHypAction hideHypAction = makeHideHypAction(singleton(pred));
		final Predicate notImpRight = Lib.makeNeg(Lib.impRight(pred));
		final Predicate notImpLeft = Lib.makeNeg(Lib.impLeft(pred));
		final Set<Predicate> addedHyps = new LinkedHashSet<Predicate>();
		addedHyps.addAll(Lib.breakPossibleConjunct(notImpRight));
		addedHyps.addAll(Lib.breakPossibleConjunct(notImpLeft));
		
		return new IAntecedent[] {
				ProverFactory.makeAntecedent(
						notImpRight,null,
						hideHypAction),
				ProverFactory.makeAntecedent(
						null,
						addedHyps,
						hideHypAction)
		};

	}

	@Override
	protected String getDisplay(Predicate pred) {
		return "⇒ hyp mt (" + pred + ")";
	}
	
	@Override
	protected boolean isGoalDependent(IProverSequent sequent, Predicate pred) {
		return false;
	}

	public int getVersion() {
		return VERSION;
	}

}
